### ISSUE TITLE
Build checks fail when opening PRs

### ISSUE THREAD

**Issue by bkjoel** [Soluto/airbag#103]
Airbag looks to have 2 workflows configured for `codefresh` under `deployments/codefresh`.
currently `test.yaml` has a 0% success rate - 
![image](https://user-images.githubusercontent.com/27892030/175257423-1d699a8e-b4e5-4294-a587-d2c68e838649.png)

@Mordech said this also appears to be a problem in other repos in our public organization.

**Comment by AmitBenAmi** [comment]
Done, see #113
