### ISSUE TITLE
Not able to call API from Airbag

### ISSUE THREAD

**Issue by murughas** [Soluto/airbag#45]
Hi,
 var response = await ExecuteQuery(mConfiguration.QueryPath, request);

            switch (mConfiguration.Mode)
            {
                case AuthorizationMode.Disabled:
                case AuthorizationMode.LogOnly:
                case AuthorizationMode.Enabled when response == OpaQueryResult.Allowed:
                    await _next(context);
                    break;

I am getting a response as allowed, but the next step is not calling my localhost API, throwing internal server error

**Exception Details:**
An unhandled exception occurred while processing the request.
SocketException: The I/O operation has been aborted because of either a thread exit or an application request
IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.
System.Net.Sockets.Socket&#x2B;AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

**Proxy Settings:**
var proxyOptions = new ProxyOptions
            {
                Scheme = "http",
                Host = _configuration.GetValue("BACKEND_HOST_NAME", "localhost"),
                Port = _configuration.GetValue("BACKEND_SERVICE_PORT", "44337")
            };
can anyone give suggestion to resolve this issue.

**Comment by omerlh** [comment]
Did you set `BACKEND_HOST_NAME` and `BACKEND_SERVICE_PORT` or is you API is on the same pod and listen on 44337?

**Comment by murughas** [comment]
yes, I set BACKEND_HOST_NAME and BACKEND_SERVICE_PORT, I did not deploy airbag and API in a pod, I am running all the API's (sampleAuthServer, Airbag and Sample API) locally.

**Comment by omerlh** [comment]
ohhh you mean you're trying to run the tests?

**Comment by murughas** [comment]
> ohhh you mean you're trying to run the tests?
yes

**Comment by murughas** [comment]
its working now

**Comment by omerlh** [comment]
Happy to hear so!
